/* 
 * Copyright 2012 Mohawk College of Applied Arts and Technology
 * 
 * Licensed under the Apache License, Version 2.0 (the "License"); you 
 * may not use this file except in compliance with the License. You may 
 * obtain a copy of the License at 
 * 
 * http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the 
 * License for the specific language governing permissions and limitations under 
 * the License.
 * 
 */

package ihe.iti.xds_b._2007;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DocumentRegistry_Service", targetNamespace = "urn:ihe:iti:xds-b:2007", wsdlLocation = "file:/C:/Users/Mohamed/Documents/NetBeansProjects/SharedHealthComponents/XDS/src/ca/marc/ihe/xds/resources/ihe/wsdl/XDS.b_DocumentRegistry.wsdl")
public class DocumentRegistryService
    extends Service
{

    private final static URL DOCUMENTREGISTRYSERVICE_WSDL_LOCATION;
    private final static WebServiceException DOCUMENTREGISTRYSERVICE_EXCEPTION;
    private final static QName DOCUMENTREGISTRYSERVICE_QNAME = new QName("urn:ihe:iti:xds-b:2007", "DocumentRegistry_Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Mohamed/Documents/NetBeansProjects/SharedHealthComponents/XDS/src/ca/marc/ihe/xds/resources/ihe/wsdl/XDS.b_DocumentRegistry.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DOCUMENTREGISTRYSERVICE_WSDL_LOCATION = url;
        DOCUMENTREGISTRYSERVICE_EXCEPTION = e;
    }

    public DocumentRegistryService() {
        super(__getWsdlLocation(), DOCUMENTREGISTRYSERVICE_QNAME);
    }

    public DocumentRegistryService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DOCUMENTREGISTRYSERVICE_QNAME, features);
    }

    public DocumentRegistryService(URL wsdlLocation) {
        super(wsdlLocation, DOCUMENTREGISTRYSERVICE_QNAME);
    }

    public DocumentRegistryService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DOCUMENTREGISTRYSERVICE_QNAME, features);
    }

    public DocumentRegistryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocumentRegistryService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DocumentRegistryPortType
     */
    @WebEndpoint(name = "DocumentRegistry_Port_Soap11")
    public DocumentRegistryPortType getDocumentRegistryPortSoap11() {
        return super.getPort(new QName("urn:ihe:iti:xds-b:2007", "DocumentRegistry_Port_Soap11"), DocumentRegistryPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocumentRegistryPortType
     */
    @WebEndpoint(name = "DocumentRegistry_Port_Soap11")
    public DocumentRegistryPortType getDocumentRegistryPortSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("urn:ihe:iti:xds-b:2007", "DocumentRegistry_Port_Soap11"), DocumentRegistryPortType.class, features);
    }

    /**
     * 
     * @return
     *     returns DocumentRegistryPortType
     */
    @WebEndpoint(name = "DocumentRegistry_Port_Soap12")
    public DocumentRegistryPortType getDocumentRegistryPortSoap12() {
        return super.getPort(new QName("urn:ihe:iti:xds-b:2007", "DocumentRegistry_Port_Soap12"), DocumentRegistryPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocumentRegistryPortType
     */
    @WebEndpoint(name = "DocumentRegistry_Port_Soap12")
    public DocumentRegistryPortType getDocumentRegistryPortSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("urn:ihe:iti:xds-b:2007", "DocumentRegistry_Port_Soap12"), DocumentRegistryPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DOCUMENTREGISTRYSERVICE_EXCEPTION!= null) {
            throw DOCUMENTREGISTRYSERVICE_EXCEPTION;
        }
        return DOCUMENTREGISTRYSERVICE_WSDL_LOCATION;
    }

}
